#cloud-config
write_files:
  - path: /etc/consul.d/consul.json
    content: ${consul_conf}
    permissions: '0644'
    owner: consul:consul
    encoding: b64
  - path: /etc/consul.d/ca.pem
    content: ${ca_file}
    permissions: '0644'
    owner: consul:consul
    encoding: b64
  - path: /etc/consul.d/web-server.json
    content: ${web_service}
    permissions: '0644'
    owner: consul:consul
    encoding: b64

runcmd:
  - "sed -i 's/\"./ca.pem\"/\"/etc/consul.d/ca.pem\"/g' /etc/consul.d/consul.json"
  - "cp /etc/consul.d/consul.json /etc/consul.d/consul.txt"
  - "systemctl enable consul"
  - "systemctl restart consul"